# Generated by Django 4.0.4 on 2022-06-01 06:49

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stocks', '0002_alter_stocks_stock_symbol'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='stocks',
            unique_together={('user', 'stock_symbol', 'company_name')},
        ),
    ]
