# Generated by Django 4.0.4 on 2022-08-05 05:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stocks', '0003_alter_stocks_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='stocks',
            unique_together={('user', 'stock_symbol')},
        ),
        migrations.AlterField(
            model_name='stocks',
            name='company_name',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
