# Generated by Django 4.0.4 on 2022-08-09 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0004_alter_stocks_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stocks',
            name='stock_symbol',
            field=models.CharField(max_length=10),
        ),
    ]
