version: "3.9"

services:
  backend:
    restart: always
    container_name: favorite_stock_backend
    env_file:
      - ./backend/.env
    build:
      context: ./backend/
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - stock-net

  db:
    restart: always
    container_name: favorite_stock_db
    image: postgres:10-alpine
    environment:
      - POSTGRES_DB=stock-app-db
      - POSTGRES_USER=default
      - POSTGRES_PASSWORD=supersecretpassword
    ports: -"5432:5432"
    networks:
      - stock-net

  networks:
    stock-net:
      driver: bridge
