version: "3"

services:
  backend:
    restart: no
    container_name: favorite_stock_backend
    env_file:
      - ./backend/.env
    environment:
      - DJANGO_SUPERUSER_EMAIL=testemail@example.com
      - DJANGO_SUPERUSER_PASSWORD=testpass
    build:
      context: ./backend/
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    command: >
      sh -c "python3 manage.py wait_for_db &&
            python3 manage.py migrate &&
            python3 manage.py add_test_admin&&
            python3 manage.py runserver 0.0.0.0:8000
            "
    depends_on:
      - db

  db:
    restart: no
    container_name: favorite_stock_db
    image: postgres:10-alpine
    environment:
      - POSTGRES_DB=stock-app-db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=supersecretpassword
    ports:
      - "5432:5432"
